export let Top50Companies:string[]=[
'Apple',
'Microsoft',
'Alphabet',
'Amazon',
'Tesla',
'Nvidia',
'Meta',
'Broadcom',
'ASML Holding',
'AstraZeneca',
'Costco',
'Cisco',
'T-Mobile',
'Verizon',
'Adobe Inc',
'Comcast',
'Texas',
'Amgen',
'Netflix',
'Sanofi',
'Qualcomm',
'Pinduoduo',
'Starbucks',
'Intel',
'Intuit',
'Gilead',
'JD',
'Advanced Micro Devices',
'Automatic Data Processing',
'Intuitive Surgical',
'Mondelez International',
'Analog Devices',
'Conversion Labs',
'Applied materials',
'PayPal',
'Regeneron Pharmaceuticals',
'Vertex Pharmaceuticals',
'Moderna',
'Equini',
'CME Group',
'Lam Research Corporation',
'Micron Technology',
'Airbnb',
'KLA Corporation',
'Monster Beverage Corporation'
]


